language: node_js
node_js:
- '6'
services:
- mongodb
install:
- npm install
script:
- npm run test
env:
- NODE_ENV=development
deploy:
  provider: heroku
  api_key:
    secure: 'XjGeAJKTu/GSLL3rDKhO+xS1/gDcK4kYo+oqcbJTN+m4sLqDOfAuh6EwgBmVA4cuTpTpw3O0kvPT2BldijLFZuL6wWhdWxm4azezoKPuDhlf4b1xe1jaZebkfp2/vFBPRYG+9UxYq3G2aZmkNTWkKqttc+gH1ctGoBBLESLGnoFx7uwPVBtprp1c33HIjtQ4Of9jeOw3Y7PGG24cix99CejtBEETjrRFS1xyJ3sd+LXJrnExTs9m/guWOviGoUrLxManN/Pfj4Zmes6mnj3lBBhhWL4n7SD3HeC4qAewod9In5pntSe2sOYXTdF3wiYPoMYqZKkqmUqQAW48daWioWxQ1YHeAhQhcWSApcS9N+zeRIL9du3I8i7gtzOpqQ0mzWiX13rKDf7rleS1shM+cetOheUqqK6dKnn46+1/NvSv+HlMGHHgw1+y4VbgXvmnkTn+dFXEVu78mbk6F6odWQZCM8kc+/g3CbOwcdnoNMrTIc2zclt48HPI77AKtFx8UoUzVkOkJFlpwK8mX8at9LDH4SfJ7C3K+3Ex35cTb/O7w9sIQ6QrtjFdLi3GUxi/75HFq3LFC8FDXOHK5yi/AyRT3vthzpo3Hq2h3PR788DFa0SRsGWKOn3UB7brv38o0FnX+e2yDj5vGA/PZA0WeqiH1cN9aK2xqE5AzBTdLzo='
  on: master
  app: team5quests
